"""
build_vrp_notebook.py
─────────────────────
Generate notebook 06_vrp.ipynb
"""
import json, os

os.makedirs('notebooks', exist_ok=True)

def md(src):
    return {"cell_type":"markdown","metadata":{},"source": src if isinstance(src,list) else [src]}

def code(src, outputs=None):
    return {"cell_type":"code","execution_count":None,"metadata":{},
            "outputs": outputs or [],"source": src if isinstance(src,list) else [src]}

def nb(cells):
    return {"nbformat":4,"nbformat_minor":5,
            "metadata":{"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},
                        "language_info":{"name":"python","version":"3.10.0"}},
            "cells": cells}

SETUP = code([
    "import sys, os\n",
    "sys.path.insert(0, os.path.abspath('..'))\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import matplotlib.gridspec as gridspec\n",
    "from scipy.stats import norm\n",
    "from src.data_loader import load_data\n",
    "from src.plotting    import *\n",
    "from src.metrics     import compute_metrics\n",
    "from src.strategy_vrp import (\n",
    "    build_short_straddle, build_variance_swap,\n",
    "    compute_vrp_signal, compute_fair_variance_strike,\n",
    "    realized_vol_cc, realized_vol_parkinson\n",
    ")\n",
    "\n",
    "DATA_PATH = '../data/spy_simulated_2020_2022.csv'\n",
    "# DATA_PATH = '../data/spy_2020_2022.csv'  # real data\n",
    "\n",
    "df = load_data(DATA_PATH)\n",
    "print('Loaded:', df.shape)"
])

cells = [

# ── TITLE ────────────────────────────────────────────────────────────
md([
    "# ⚡ Notebook 6 — Variance Risk Premium (VRP)\n",
    "> Two implementations: **Short Straddle** and **Synthetic Variance Swap**\n\n",
    "---\n",
    "\n",
    "| Approach | Mechanism | Complexity |\n",
    "|---|---|---|\n",
    "| **Short Straddle** | Sell ATM call + put weekly | Simple |\n",
    "| **Variance Swap** | 1/K² replication of log-contract | Advanced |\n",
    "\n",
    "**Core thesis**: Implied volatility is systematically higher than realized volatility on equity indices.\n",
    "Selling volatility earns the **variance risk premium** (VRP)."
]),

# ── PART 1: THEORY VRP ────────────────────────────────────────────────
md([
    "---\n",
    "# Part 1 — Theory of the Variance Risk Premium\n",
    "---"
]),

md([
    "## 1.1 Definition\n",
    "\n",
    "The **variance risk premium** is defined as:\n",
    "\n",
    "$$\\text{VRP}_t = \\sigma^{\\text{IV}}_t - \\sigma^{\\text{RV}}_{t+T}$$\n",
    "\n",
    "Empirically on equity indices, $\\mathbb{E}[\\text{VRP}] > 0$:\n",
    "options are systematically overpriced relative to realized volatility.\n",
    "\n",
    "### Why does VRP exist?\n",
    "- **Demand for insurance**: investors pay a premium to hedge tail risk\n",
    "- **Jump risk**: options price jump risk not captured by diffusion models\n",
    "- **Ambiguity aversion**: buyers pay extra for uncertainty about volatility itself\n",
    "- **Institutional hedging**: systematic demand for puts keeps IV elevated\n",
    "\n",
    "### Two estimators of realized volatility\n",
    "\n",
    "| Estimator | Formula | Properties |\n",
    "|---|---|---|\n",
    "| **Close-to-Close** | $\\hat{\\sigma}_{cc} = \\text{std}(\\log R_t) \\cdot \\sqrt{252}$ | Simple, noisy |\n",
    "| **Parkinson** | $\\hat{\\sigma}_{park} = \\sqrt{\\frac{252}{4\\ln 2} \\cdot \\mathbb{E}[(\\ln H/L)^2]}$ | 5x more efficient, uses range |"
]),

SETUP,

# ── VRP SIGNAL ANALYSIS ───────────────────────────────────────────────
md(["## 1.2 VRP Signal Analysis\n"]),

code([
    "vrp = compute_vrp_signal(df, window=21)\n",
    "print('VRP signal stats:')\n",
    "print(vrp[['iv_atm','rv_cc','rv_park','vrp_cc','vrp_park']]\n",
    "      .describe().round(4).to_string())\n",
    "print()\n",
    "print(f'VRP > 0 (cc)  : {(vrp.vrp_cc   > 0).mean():.1%} of days')\n",
    "print(f'VRP > 0 (park): {(vrp.vrp_park > 0).mean():.1%} of days')"
]),

code([
    "fig = plt.figure(figsize=(16, 10), facecolor=BG)\n",
    "gs  = gridspec.GridSpec(3, 2, figure=fig, hspace=0.48, wspace=0.32)\n",
    "\n",
    "# Panel 1: IV vs RV over time\n",
    "ax1 = fig.add_subplot(gs[0, :])\n",
    "ax1.plot(vrp.index, vrp['iv_atm']*100,   color=GOLD,   lw=2,   label='ATM Implied Vol (IV)')\n",
    "ax1.plot(vrp.index, vrp['rv_cc']*100,    color=RED,    lw=1.4, label='Realized Vol CC 21d', alpha=0.8)\n",
    "ax1.plot(vrp.index, vrp['rv_park']*100,  color=GREEN,  lw=1.4, label='Realized Vol Parkinson 21d', alpha=0.8)\n",
    "ax1.fill_between(vrp.index, vrp['iv_atm']*100, vrp['rv_park']*100,\n",
    "                 where=vrp['iv_atm'] >= vrp['rv_park'],\n",
    "                 alpha=0.15, color=GREEN, label='VRP (park) > 0')\n",
    "ax1.fill_between(vrp.index, vrp['iv_atm']*100, vrp['rv_park']*100,\n",
    "                 where=vrp['iv_atm'] <  vrp['rv_park'],\n",
    "                 alpha=0.15, color=RED, label='VRP (park) < 0')\n",
    "style_ax(ax1, 'Implied vs Realized Volatility — SPY 2020–2022 (%)', fontsize=11)\n",
    "legend(ax1, fontsize=9)\n",
    "\n",
    "# Panel 2: VRP spread\n",
    "ax2 = fig.add_subplot(gs[1, 0])\n",
    "ax2.bar(vrp.index, vrp['vrp_park']*100,\n",
    "        color=[GREEN if v > 0 else RED for v in vrp['vrp_park']],\n",
    "        alpha=0.7, width=1, label='VRP Parkinson')\n",
    "ax2.axhline(vrp['vrp_park'].mean()*100, color=GOLD, lw=1.5, ls='--',\n",
    "            label=f'Mean={vrp[\"vrp_park\"].mean()*100:.2f}%')\n",
    "style_ax(ax2, 'VRP Spread = IV - RV Parkinson (%)')\n",
    "legend(ax2)\n",
    "\n",
    "# Panel 3: VRP CC spread\n",
    "ax3 = fig.add_subplot(gs[1, 1])\n",
    "ax3.bar(vrp.index, vrp['vrp_cc']*100,\n",
    "        color=[GREEN if v > 0 else RED for v in vrp['vrp_cc']],\n",
    "        alpha=0.7, width=1)\n",
    "ax3.axhline(vrp['vrp_cc'].mean()*100, color=GOLD, lw=1.5, ls='--',\n",
    "            label=f'Mean={vrp[\"vrp_cc\"].mean()*100:.2f}%')\n",
    "style_ax(ax3, 'VRP Spread = IV - RV Close-to-Close (%)')\n",
    "legend(ax3)\n",
    "\n",
    "# Panel 4: IV histogram\n",
    "ax4 = fig.add_subplot(gs[2, 0])\n",
    "ax4.hist(vrp['iv_atm']*100,   bins=50, color=GOLD,  alpha=0.6, label='IV', density=True)\n",
    "ax4.hist(vrp['rv_park']*100,  bins=50, color=GREEN, alpha=0.5, label='RV Parkinson', density=True)\n",
    "ax4.hist(vrp['rv_cc']*100,    bins=50, color=RED,   alpha=0.4, label='RV CC', density=True)\n",
    "style_ax(ax4, 'Distribution of Volatility Estimates (%)')\n",
    "legend(ax4)\n",
    "\n",
    "# Panel 5: VRP autocorrelation\n",
    "ax5 = fig.add_subplot(gs[2, 1])\n",
    "lags = range(1, 31)\n",
    "acf_cc   = [vrp['vrp_cc'].autocorr(lag=l)   for l in lags]\n",
    "acf_park = [vrp['vrp_park'].autocorr(lag=l) for l in lags]\n",
    "ax5.bar([l-0.2 for l in lags], acf_cc,   0.4, color=RED,  alpha=0.7, label='VRP CC')\n",
    "ax5.bar([l+0.2 for l in lags], acf_park, 0.4, color=GREEN,alpha=0.7, label='VRP Parkinson')\n",
    "ax5.axhline(0, color=GREY, lw=0.8)\n",
    "ax5.axhline(1.96/np.sqrt(len(vrp)), color=WHITE, lw=1, ls=':', alpha=0.6)\n",
    "ax5.axhline(-1.96/np.sqrt(len(vrp)), color=WHITE, lw=1, ls=':', alpha=0.6)\n",
    "style_ax(ax5, 'Autocorrelation of VRP Signal')\n",
    "ax5.set_xlabel('Lag (days)')\n",
    "legend(ax5)\n",
    "\n",
    "fig.suptitle('Variance Risk Premium (VRP) Analysis — SPY 2020–2022',\n",
    "             color=WHITE, fontsize=13, fontweight='bold')\n",
    "fig.patch.set_facecolor(BG)\n",
    "plt.tight_layout()\n",
    "plt.savefig('../outputs/vrp_signal_analysis.png', dpi=150, bbox_inches='tight', facecolor=BG)\n",
    "plt.show()"
]),

# ── PART 2: SHORT STRADDLE ────────────────────────────────────────────
md([
    "---\n",
    "# Part 2 — Strategy A: Short Straddle\n",
    "---"
]),

md([
    "## 2.1 Mechanics\n",
    "\n",
    "Sell **both** legs of the ATM straddle each week:\n",
    "\n",
    "$$\\Pi_{\\text{short straddle}} = (c + p) - |S_T - K|$$\n",
    "\n",
    "Profitable when $|S_T - K| < c + p$, i.e. when SPY moves **less than the implied move**.\n",
    "\n",
    "**Greeks:** Δ≈0, Γ<<0, Θ>>0, ν<<0 — maximum short vega, maximum long theta.\n",
    "\n",
    "This is the **mirror image** of the Long Straddle (notebook 04).\n",
    "\n",
    "**Relationship to VRP**: The expected P&L of one short straddle cycle is:\n",
    "\n",
    "$$\\mathbb{E}[\\Pi] \\approx \\text{Notional} \\times (\\sigma^{\\text{IV}} - \\sigma^{\\text{RV}}) \\times \\sqrt{T}$$"
]),

code([
    "# Payoff diagrams for short straddle\n",
    "fig, axes = plt.subplots(1, 2, figsize=(14, 5), facecolor=BG)\n",
    "\n",
    "K, c, p = 100, 3.2, 3.0\n",
    "tot = c + p\n",
    "ST  = np.linspace(75, 130, 500)\n",
    "\n",
    "# Short straddle payoff\n",
    "pnl_short = tot - np.abs(ST - K)\n",
    "pnl_long  = np.abs(ST - K) - tot  # mirror\n",
    "\n",
    "ax = axes[0]\n",
    "ax.plot(ST, pnl_short, color=RED,  lw=2.5, label='Short Straddle (VRP harvest)')\n",
    "ax.plot(ST, pnl_long,  color=GOLD, lw=1.5, ls='--', label='Long Straddle (mirror)', alpha=0.7)\n",
    "ax.fill_between(ST, pnl_short, 0, where=pnl_short>0, alpha=0.2, color=GREEN)\n",
    "ax.fill_between(ST, pnl_short, 0, where=pnl_short<0, alpha=0.2, color=RED)\n",
    "ax.axvline(K-tot, color=WHITE, lw=1, ls=':', alpha=0.6, label=f'BE: {K-tot} / {K+tot}')\n",
    "ax.axvline(K+tot, color=WHITE, lw=1, ls=':', alpha=0.6)\n",
    "style_ax(ax, 'Short Straddle P&L at Expiration')\n",
    "ax.set_xlabel('SPY at expiry'); ax.set_ylabel('P&L ($)')\n",
    "legend(ax)\n",
    "\n",
    "# Profit zone\n",
    "ax2 = axes[1]\n",
    "moves = np.linspace(-0.20, 0.20, 300) * 100\n",
    "ax2.plot(moves, tot - np.abs(moves/100 * K), color=RED, lw=2.5, label='Short Straddle')\n",
    "ax2.axhline(0, color=GREY, lw=0.8)\n",
    "ax2.fill_between(moves, tot - np.abs(moves/100 * K), 0,\n",
    "                 where=(tot - np.abs(moves/100 * K)) > 0, alpha=0.2, color=GREEN)\n",
    "ax2.axvline(-(tot/K)*100, color=WHITE, lw=1, ls=':', alpha=0.6)\n",
    "ax2.axvline( (tot/K)*100, color=WHITE, lw=1, ls=':', alpha=0.6)\n",
    "ax2.annotate(f'Profit zone\\n±{tot/K*100:.1f}% move',\n",
    "             xy=(0, tot*0.5), ha='center', color=GREEN, fontsize=9)\n",
    "style_ax(ax2, f'P&L vs % Move (K={K}, total prem={tot})')\n",
    "ax2.set_xlabel('SPY move (%)')\n",
    "legend(ax2)\n",
    "\n",
    "fig.suptitle('Short Straddle — VRP Harvesting Strategy',\n",
    "             color=WHITE, fontsize=12, fontweight='bold')\n",
    "fig.patch.set_facecolor(BG)\n",
    "plt.tight_layout(); plt.show()"
]),

md(["## 2.2 Backtest — Short Straddle\n"]),

code([
    "ss = build_short_straddle(df, target_dte=7)\n",
    "ss[['spy_price','index_level','spy_bnh','strike','total_premium','call_iv']].head(15)"
]),

code([
    "fig = plt.figure(figsize=(18, 11), facecolor=BG)\n",
    "gs  = gridspec.GridSpec(3, 2, figure=fig, hspace=0.48, wspace=0.32)\n",
    "\n",
    "# Panel 1: Index vs SPY\n",
    "ax1 = fig.add_subplot(gs[0, :])\n",
    "ax1.plot(ss.index, ss['index_level'], color=RED,  lw=2,   label='Short Straddle (VRP)')\n",
    "ax1.plot(ss.index, ss['spy_bnh'],     color=BLUE, lw=1.4, label='SPY B&H', alpha=0.8, ls='--')\n",
    "ax1.axhline(100, color=GREY, lw=0.8, ls=':')\n",
    "style_ax(ax1, 'Short Straddle Index vs SPY B&H (Base=100)', fontsize=11)\n",
    "legend(ax1, fontsize=9)\n",
    "\n",
    "# Panel 2: Drawdown\n",
    "ax2 = fig.add_subplot(gs[1, 0])\n",
    "dd_ss  = (ss['index_level'] / ss['index_level'].cummax() - 1) * 100\n",
    "dd_spy = (ss['spy_bnh']     / ss['spy_bnh'].cummax()     - 1) * 100\n",
    "ax2.fill_between(ss.index, dd_ss,  0, color=RED,  alpha=0.35, label='Short Straddle')\n",
    "ax2.fill_between(ss.index, dd_spy, 0, color=BLUE, alpha=0.18, label='SPY')\n",
    "ax2.plot(ss.index, dd_ss,  color=RED,  lw=0.9)\n",
    "ax2.plot(ss.index, dd_spy, color=BLUE, lw=0.9)\n",
    "style_ax(ax2, 'Drawdown (%)')\n",
    "legend(ax2)\n",
    "\n",
    "# Panel 3: Rolling P&L per roll\n",
    "ax3 = fig.add_subplot(gs[1, 1])\n",
    "roll_pnl = ss['cash'].diff().dropna()\n",
    "roll_pnl = roll_pnl[roll_pnl.abs() > 0.1]  # only roll days\n",
    "colors_pnl = [GREEN if v > 0 else RED for v in roll_pnl]\n",
    "ax3.bar(roll_pnl.index, roll_pnl, color=colors_pnl, alpha=0.7, width=5)\n",
    "ax3.axhline(0, color=GREY, lw=0.8)\n",
    "ax3.axhline(roll_pnl.mean(), color=GOLD, lw=1.5, ls='--',\n",
    "            label=f'Avg P&L={roll_pnl.mean():.2f}')\n",
    "style_ax(ax3, 'P&L per Cycle (Cash Settlement)')\n",
    "legend(ax3)\n",
    "\n",
    "# Panel 4: Premium collected over time\n",
    "ax4 = fig.add_subplot(gs[2, 0])\n",
    "prem = ss['total_premium'].dropna()\n",
    "ax4.plot(prem.index, prem, color=GOLD, lw=1.2, alpha=0.6)\n",
    "ax4.fill_between(prem.index, 0, prem, color=GOLD, alpha=0.2)\n",
    "ax4.axhline(prem.mean(), color=RED, lw=1.5, ls='--',\n",
    "            label=f'Avg premium={prem.mean():.2f}')\n",
    "style_ax(ax4, 'Weekly Straddle Premium ($)')\n",
    "legend(ax4)\n",
    "\n",
    "# Panel 5: VRP signal vs strategy returns\n",
    "ax5 = fig.add_subplot(gs[2, 1])\n",
    "ss_ret  = ss['index_level'].pct_change().dropna()\n",
    "vrp_sig = vrp['vrp_park'].reindex(ss_ret.index).fillna(method='ffill')\n",
    "valid   = ~(ss_ret.isna() | vrp_sig.isna())\n",
    "ax5.scatter(vrp_sig[valid]*100, ss_ret[valid]*100,\n",
    "            color=RED, alpha=0.3, s=8)\n",
    "z = np.polyfit(vrp_sig[valid], ss_ret[valid], 1)\n",
    "xline = np.linspace(vrp_sig[valid].min(), vrp_sig[valid].max(), 100)\n",
    "ax5.plot(xline*100, np.polyval(z, xline)*100, color=GOLD, lw=2)\n",
    "style_ax(ax5, 'VRP Signal vs Daily Strategy Returns')\n",
    "ax5.set_xlabel('VRP Parkinson (%)')\n",
    "ax5.set_ylabel('Strategy daily return (%)')\n",
    "\n",
    "fig.suptitle('Short Straddle VRP — Performance Dashboard',\n",
    "             color=WHITE, fontsize=13, fontweight='bold', y=0.998)\n",
    "fig.patch.set_facecolor(BG)\n",
    "plt.tight_layout()\n",
    "plt.savefig('../outputs/vrp_short_straddle.png', dpi=150, bbox_inches='tight', facecolor=BG)\n",
    "plt.show()"
]),

# ── PART 3: VARIANCE SWAP ─────────────────────────────────────────────
md([
    "---\n",
    "# Part 3 — Strategy B: Synthetic Variance Swap\n",
    "---"
]),

md([
    "## 3.1 Theory — Log-Contract Replication\n",
    "\n",
    "A **variance swap** pays the difference between realized and implied variance at expiration:\n",
    "\n",
    "$$\\Pi_{\\text{var swap}} = N_{\\text{var}} \\times (\\sigma^2_{\\text{RV}} - K_{\\text{var}})$$\n",
    "\n",
    "where $K_{\\text{var}}$ is the **fair variance strike** computed at inception.\n",
    "\n",
    "### Replication via the log-contract (Demeterfi et al. 1999)\n",
    "\n",
    "The fair variance strike is replicated by a static portfolio of OTM options:\n",
    "\n",
    "$$K_{\\text{var}} = \\frac{2}{T} \\left[\n",
    "    \\sum_{\\text{puts}} \\frac{\\Delta K_i}{K_i^2} P(K_i)\n",
    "  + \\sum_{\\text{calls}} \\frac{\\Delta K_i}{K_i^2} C(K_i)\n",
    "\\right]$$\n",
    "\n",
    "This is exactly the **CBOE VIX² methodology** (with some adjustments).\n",
    "\n",
    "### Short variance = VRP harvest\n",
    "\n",
    "We **sell variance** at $K_{\\text{var}}$ each month. If $\\sigma^{\\text{IV}} > \\sigma^{\\text{RV}}$ on average:\n",
    "\n",
    "$$\\mathbb{E}[\\Pi_{\\text{short var}}] = N_{\\text{var}} \\times (K_{\\text{var}} - \\mathbb{E}[\\sigma^2_{\\text{RV}}]) > 0$$\n",
    "\n",
    "### Notional convention\n",
    "\n",
    "We size by **vega notional** $N_{\\nu}$ (\\$ per 1 vol point):\n",
    "\n",
    "$$N_{\\text{var}} = \\frac{N_{\\nu}}{2 \\cdot K_{\\text{vol}}}$$"
]),

code([
    "# Visualize the replication: option weights 1/K^2\n",
    "fig, axes = plt.subplots(1, 2, figsize=(14, 5), facecolor=BG)\n",
    "\n",
    "# Get one day's chain for illustration\n",
    "from src.data_loader import get_day\n",
    "sample_date = sorted(df['QUOTE_DATE'].unique())[100]\n",
    "df_day = get_day(df, sample_date)\n",
    "S0 = df_day['UNDERLYING_LAST'].iloc[0]\n",
    "\n",
    "# Find chain with DTE~22\n",
    "chain = df_day.copy()\n",
    "chain['_dd'] = (chain['DTE'] - 22).abs()\n",
    "best = chain['_dd'].min()\n",
    "chain = chain[chain['_dd'] == best].sort_values('STRIKE')\n",
    "\n",
    "K = chain['STRIKE'].values\n",
    "C = chain['C_MID'].values\n",
    "P = chain['P_MID'].values\n",
    "\n",
    "# Weight = 1/K^2\n",
    "w = 1.0 / (K**2)\n",
    "\n",
    "ax = axes[0]\n",
    "ax.bar(K[K < S0], w[K < S0] * P[K < S0] * 1e6,\n",
    "       color=RED, alpha=0.7, width=0.8, label='OTM Puts × 1/K²')\n",
    "ax.bar(K[K >= S0], w[K >= S0] * C[K >= S0] * 1e6,\n",
    "       color=BLUE, alpha=0.7, width=0.8, label='OTM Calls × 1/K²')\n",
    "ax.axvline(S0, color=GOLD, lw=2, ls='--', label=f'ATM S={S0:.0f}')\n",
    "style_ax(ax, f'Option Contributions to K_var (date={sample_date.date()})')\n",
    "ax.set_xlabel('Strike K'); ax.set_ylabel('Contribution (×10⁻⁶)')\n",
    "legend(ax)\n",
    "\n",
    "# The 1/K^2 weight function\n",
    "ax2 = axes[1]\n",
    "K_range = np.linspace(S0 * 0.7, S0 * 1.3, 300)\n",
    "ax2.plot(K_range, 1/(K_range**2) * 1e6, color=GOLD, lw=2.5, label='1/K² weight')\n",
    "ax2.fill_between(K_range[K_range < S0], 0, 1/(K_range[K_range < S0]**2) * 1e6,\n",
    "                 alpha=0.2, color=RED, label='Put region')\n",
    "ax2.fill_between(K_range[K_range >= S0], 0, 1/(K_range[K_range >= S0]**2) * 1e6,\n",
    "                 alpha=0.2, color=BLUE, label='Call region')\n",
    "ax2.axvline(S0, color=GOLD, lw=1.5, ls='--')\n",
    "style_ax(ax2, 'Replication Weight Function 1/K² (×10⁻⁶)')\n",
    "ax2.set_xlabel('Strike K')\n",
    "legend(ax2)\n",
    "\n",
    "fig.suptitle('Variance Swap: Log-Contract Replication',\n",
    "             color=WHITE, fontsize=12, fontweight='bold')\n",
    "fig.patch.set_facecolor(BG)\n",
    "plt.tight_layout(); plt.show()\n",
    "\n",
    "# Show K_var computation\n",
    "vs_info = compute_fair_variance_strike(df_day, target_dte=22)\n",
    "print(f'Fair Variance Strike  K_var = {vs_info[\"K_var\"]:.6f}')\n",
    "print(f'Fair Vol Strike       K_vol = {vs_info[\"K_vol\"]:.4f}  ({vs_info[\"K_vol\"]*100:.2f}%)')\n",
    "print(f'ATM Implied Vol              = {vs_info[\"iv_atm\"]*100:.2f}%')\n",
    "print(f'Convexity adj (K_vol - IV)   = {(vs_info[\"K_vol\"] - vs_info[\"iv_atm\"])*100:.3f}%')"
]),

md(["## 3.2 Backtest — Synthetic Variance Swap (Short)\n"]),

code([
    "vs = build_variance_swap(df, target_dte=22, notional_vega=1000, r=0.04)\n",
    "vs[['spy_price','index_level','K_vol','rv_running','vrp_live','mtm_pnl']].head(15)"
]),

code([
    "fig = plt.figure(figsize=(18, 11), facecolor=BG)\n",
    "gs  = gridspec.GridSpec(3, 2, figure=fig, hspace=0.48, wspace=0.32)\n",
    "\n",
    "# Panel 1: Index\n",
    "ax1 = fig.add_subplot(gs[0, :])\n",
    "ax1.plot(vs.index, vs['index_level'], color=PURPLE, lw=2,   label='Short Variance Swap')\n",
    "ax1.plot(vs.index, vs['spy_bnh'],     color=BLUE,   lw=1.4, label='SPY B&H', alpha=0.8, ls='--')\n",
    "ax1.axhline(100, color=GREY, lw=0.8, ls=':')\n",
    "style_ax(ax1, 'Short Variance Swap Index vs SPY B&H (Base=100)', fontsize=11)\n",
    "legend(ax1, fontsize=9)\n",
    "\n",
    "# Panel 2: K_vol vs RV running\n",
    "ax2 = fig.add_subplot(gs[1, 0])\n",
    "ax2.plot(vs.index, vs['K_vol']*100,      color=GOLD,  lw=1.5, label='K_vol (fair var strike)')\n",
    "ax2.plot(vs.index, vs['rv_running']*100, color=RED,   lw=1.5, label='RV running', alpha=0.8)\n",
    "ax2.fill_between(vs.index,\n",
    "    vs['K_vol'].fillna(0)*100, vs['rv_running'].fillna(0)*100,\n",
    "    where=vs['K_vol'].fillna(0) >= vs['rv_running'].fillna(0),\n",
    "    alpha=0.15, color=GREEN, label='Short var profitable')\n",
    "ax2.fill_between(vs.index,\n",
    "    vs['K_vol'].fillna(0)*100, vs['rv_running'].fillna(0)*100,\n",
    "    where=vs['K_vol'].fillna(0) < vs['rv_running'].fillna(0),\n",
    "    alpha=0.15, color=RED)\n",
    "style_ax(ax2, 'K_vol vs Realized Vol Running (%)')\n",
    "legend(ax2)\n",
    "\n",
    "# Panel 3: Live VRP spread\n",
    "ax3 = fig.add_subplot(gs[1, 1])\n",
    "vrp_live = vs['vrp_live'].dropna()\n",
    "ax3.bar(vrp_live.index,\n",
    "        vrp_live * 100,\n",
    "        color=[GREEN if v > 0 else RED for v in vrp_live],\n",
    "        alpha=0.7, width=1)\n",
    "ax3.axhline(0, color=GREY, lw=0.8)\n",
    "ax3.axhline(vrp_live.mean()*100, color=GOLD, lw=1.5, ls='--',\n",
    "            label=f'Mean={vrp_live.mean()*100:.2f}%')\n",
    "style_ax(ax3, 'Live VRP = K_vol - RV_running (%)')\n",
    "legend(ax3)\n",
    "\n",
    "# Panel 4: MTM P&L\n",
    "ax4 = fig.add_subplot(gs[2, 0])\n",
    "ax4.plot(vs.index, vs['mtm_pnl'], color=PURPLE, lw=1.2)\n",
    "ax4.fill_between(vs.index, 0, vs['mtm_pnl'],\n",
    "                 where=vs['mtm_pnl'] >= 0, alpha=0.2, color=GREEN)\n",
    "ax4.fill_between(vs.index, 0, vs['mtm_pnl'],\n",
    "                 where=vs['mtm_pnl'] <  0, alpha=0.2, color=RED)\n",
    "style_ax(ax4, 'Daily Mark-to-Market P&L ($)')\n",
    "\n",
    "# Panel 5: Drawdown comparison\n",
    "ax5 = fig.add_subplot(gs[2, 1])\n",
    "dd_vs  = (vs['index_level'] / vs['index_level'].cummax() - 1) * 100\n",
    "dd_ss  = (ss['index_level'] / ss['index_level'].cummax() - 1) * 100\n",
    "dd_spy = (vs['spy_bnh']     / vs['spy_bnh'].cummax()     - 1) * 100\n",
    "ax5.plot(vs.index, dd_vs,  color=PURPLE, lw=1.5, label='Var Swap')\n",
    "ax5.plot(ss.index, dd_ss,  color=RED,    lw=1.5, label='Short Straddle')\n",
    "ax5.plot(vs.index, dd_spy, color=BLUE,   lw=1.2, label='SPY', ls='--', alpha=0.7)\n",
    "style_ax(ax5, 'Drawdown Comparison (%)')\n",
    "legend(ax5)\n",
    "\n",
    "fig.suptitle('Short Variance Swap (VRP) — Performance Dashboard',\n",
    "             color=WHITE, fontsize=13, fontweight='bold', y=0.998)\n",
    "fig.patch.set_facecolor(BG)\n",
    "plt.tight_layout()\n",
    "plt.savefig('../outputs/vrp_variance_swap.png', dpi=150, bbox_inches='tight', facecolor=BG)\n",
    "plt.show()"
]),

# ── PART 4: COMPARISON ────────────────────────────────────────────────
md([
    "---\n",
    "# Part 4 — Comparison: Short Straddle vs Variance Swap vs SPY\n",
    "---"
]),

code([
    "fig = plt.figure(figsize=(18, 12), facecolor=BG)\n",
    "gs  = gridspec.GridSpec(3, 2, figure=fig, hspace=0.48, wspace=0.32)\n",
    "\n",
    "# Panel 1: Index levels\n",
    "ax1 = fig.add_subplot(gs[0, :])\n",
    "ax1.plot(ss.index, ss['index_level'], color=RED,    lw=2,   label='Short Straddle')\n",
    "ax1.plot(vs.index, vs['index_level'], color=PURPLE, lw=2,   label='Short Variance Swap')\n",
    "ax1.plot(vs.index, vs['spy_bnh'],     color=BLUE,   lw=1.4, label='SPY B&H', ls='--', alpha=0.7)\n",
    "ax1.axhline(100, color=GREY, lw=0.6, ls=':')\n",
    "style_ax(ax1, 'VRP Strategies vs SPY (Base=100)', fontsize=11)\n",
    "legend(ax1, fontsize=9)\n",
    "\n",
    "# Panel 2: Rolling Sharpe\n",
    "ax2 = fig.add_subplot(gs[1, 0])\n",
    "for ser, col, lbl in [\n",
    "    (ss['index_level'], RED,    'Short Straddle'),\n",
    "    (vs['index_level'], PURPLE, 'Var Swap'),\n",
    "    (vs['spy_bnh'],     BLUE,   'SPY'),\n",
    "]:\n",
    "    r   = ser.pct_change().dropna()\n",
    "    sh  = r.rolling(60).mean() / r.rolling(60).std() * np.sqrt(252)\n",
    "    ax2.plot(sh.index, sh, color=col, lw=1.5, label=lbl)\n",
    "ax2.axhline(0, color=GREY, lw=0.8)\n",
    "style_ax(ax2, 'Rolling 60d Sharpe Ratio')\n",
    "legend(ax2)\n",
    "\n",
    "# Panel 3: Rolling vol\n",
    "ax3 = fig.add_subplot(gs[1, 1])\n",
    "for ser, col, lbl in [\n",
    "    (ss['index_level'], RED,    'Short Straddle'),\n",
    "    (vs['index_level'], PURPLE, 'Var Swap'),\n",
    "    (vs['spy_bnh'],     BLUE,   'SPY'),\n",
    "]:\n",
    "    vol = ser.pct_change().rolling(30).std() * np.sqrt(252) * 100\n",
    "    ax3.plot(vol.index, vol, color=col, lw=1.5, label=lbl)\n",
    "style_ax(ax3, 'Rolling 30d Volatility (%)')\n",
    "legend(ax3)\n",
    "\n",
    "# Panel 4: Metrics\n",
    "ax4 = fig.add_subplot(gs[2, :])\n",
    "ax4.axis('off'); ax4.set_facecolor(PANEL)\n",
    "\n",
    "def get_metrics_row(ser, name):\n",
    "    r    = ser.pct_change().dropna()\n",
    "    n    = len(r)\n",
    "    ann  = (1+r).prod()**(252/n) - 1\n",
    "    vol  = r.std() * np.sqrt(252)\n",
    "    sh   = ann / vol if vol > 0 else np.nan\n",
    "    mdd  = ((ser / ser.cummax()) - 1).min()\n",
    "    down = r[r<0].std() * np.sqrt(252)\n",
    "    sor  = ann / down if down > 0 else np.nan\n",
    "    var95 = np.percentile(r, 5)\n",
    "    return [name, f'{ann:.2%}', f'{vol:.2%}', f'{sh:.3f}',\n",
    "            f'{sor:.3f}', f'{mdd:.2%}', f'{var95:.3%}']\n",
    "\n",
    "rows = [\n",
    "    get_metrics_row(ss['index_level'], 'Short Straddle'),\n",
    "    get_metrics_row(vs['index_level'], 'Short Variance Swap'),\n",
    "    get_metrics_row(vs['spy_bnh'],     'SPY B&H'),\n",
    "]\n",
    "cols = ['Strategy', 'Ann. Return', 'Ann. Vol', 'Sharpe', 'Sortino', 'Max DD', 'VaR 95%']\n",
    "tbl  = ax4.table(cellText=rows, colLabels=cols,\n",
    "                 cellLoc='center', loc='center', bbox=[0, 0, 1, 1])\n",
    "tbl.auto_set_font_size(False); tbl.set_fontsize(10)\n",
    "for (r,c), cell in tbl.get_celld().items():\n",
    "    cell.set_facecolor('#1e1e1e' if r==0 else PANEL)\n",
    "    cell.set_edgecolor('#333')\n",
    "    cell.set_text_props(color=GOLD if (r>0 and c>0) else WHITE)\n",
    "ax4.set_title('Performance Summary', color=WHITE, fontsize=11, fontweight='bold', pad=8)\n",
    "\n",
    "fig.suptitle('VRP Strategies — Full Comparison',\n",
    "             color=WHITE, fontsize=13, fontweight='bold', y=0.998)\n",
    "fig.patch.set_facecolor(BG)\n",
    "plt.tight_layout()\n",
    "plt.savefig('../outputs/vrp_comparison.png', dpi=150, bbox_inches='tight', facecolor=BG)\n",
    "plt.show()\n",
    "print('All VRP outputs saved to outputs/')"
]),

]

path = 'notebooks/06_vrp.ipynb'
with open(path, 'w', encoding='utf-8') as f:
    json.dump(nb(cells), f, indent=1, default=str, ensure_ascii=False)
print(f'✅ {path}  ({len(cells)} cells)')
